language: go

sudo: false

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=atomic -race -coverprofile=coverage.out -v ./...

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.8" ]; then $HOME/gopath/bin/goveralls -covermode=count -coverprofile=coverage.out -service=travis-ci; fi;